// Phase-16 R7' — touch target axe-core audit (WCAG 2.5.5 / 2.5.8).
//
// Walks the 14 highest-traffic routes at the mobile viewport (375x812)
// and runs axe-core with the `target-size` rule promoted to "serious".
// Every violation is recorded to a single markdown report at
//   /screenshots/gate-2-evidence/r7-touch-targets/violations.md
// so the audit lives next to the Playwright PNGs.
//
// Pass criterion: zero target-size violations after the global CSS
// guard in `styles.css` (44 px floor below md) kicked in. If a violation
// remains, the test fails and the report tells the human which
// selector / which page.
//
// Authenticated routes are skipped here (covered separately in R14's
// responsive-matrix.spec.ts). This sprint focuses on the public surface.
import { test, expect } from "@playwright/test";
import { AxeBuilder } from "@axe-core/playwright";
import fs from "node:fs";
import path from "node:path";

const OUT_DIR = "/screenshots/gate-2-evidence/r7-touch-targets";

// 14 representative routes. Includes both marketing pages and the
// auth-flow shell (login / register). Workspace-only routes are
// excluded because they require a session.
const routes = [
  "/",
  "/home",
  "/programs",
  "/catalog",
  "/admissions",
  "/login",
  "/register",
  "/forgot",
  "/schools",
  "/pricing",
  "/events",
  "/help",
  "/about",
  "/faculty",
];

interface CapturedViolation {
  route: string;
  id: string;
  impact: string;
  help: string;
  nodes: { target: string; html: string; failureSummary: string }[];
}

const collected: CapturedViolation[] = [];

test.beforeAll(() => {
  try {
    fs.mkdirSync(OUT_DIR, { recursive: true });
  } catch {
    /* container fs read-only at first call — playwright will recover */
  }
});

for (const route of routes) {
  test(`touch targets at ${route}`, async ({ browser }) => {
    const ctx = await browser.newContext({
      viewport: { width: 375, height: 812 }, // iPhone 13 mini class
      // Pretend to be a Pixel-class phone so `pointer: coarse` rules
      // in any vendor CSS we depend on still fire.
      hasTouch: true,
      isMobile: true,
    });
    const page = await ctx.newPage();
    await page.goto(route, { waitUntil: "networkidle" });

    // Don't include hidden / display:none widgets — axe still flags them.
    const results = await new AxeBuilder({ page })
      .options({
        rules: {
          // Promote the rule from default "moderate" so a 43-px button is
          // a hard failure.
          "target-size": { enabled: true },
        },
      })
      .withTags(["wcag2a", "wcag2aa", "wcag21a", "wcag21aa", "wcag22aa"])
      .disableRules([
        // Out of scope for this sprint — covered by other audits or
        // intentionally not enforced (e.g. `region` for SPA route shells
        // that don't ship a landmark, `color-contrast` is a separate
        // R7'-cont. job).
        "region",
        "landmark-one-main",
        "page-has-heading-one",
      ])
      .analyze();

    const targetViolations = results.violations.filter(
      (v) => v.id === "target-size",
    );

    for (const v of targetViolations) {
      collected.push({
        route,
        id: v.id,
        impact: String(v.impact),
        help: v.help,
        nodes: v.nodes.map((n) => ({
          target: n.target.join(", "),
          html: n.html,
          failureSummary: String(n.failureSummary),
        })),
      });
    }

    expect(
      targetViolations,
      `target-size violations at ${route}: ${JSON.stringify(targetViolations.map((v) => v.nodes.map((n) => n.target)))}`,
    ).toEqual([]);

    await ctx.close();
  });
}

test.afterAll(async () => {
  // Always write the report, even if zero violations — a "clean" file
  // is the post-fix evidence the owner wants in the dossier.
  const lines: string[] = [];
  lines.push("# Phase-16 R7' — touch-target audit report");
  lines.push("");
  lines.push(`Generated by \`apps/web/tests/visual/r7-touch-targets.spec.ts\` running axe-core 4 with \`target-size\` promoted on the **public** surface (14 routes) at 375×812.`);
  lines.push("");
  if (collected.length === 0) {
    lines.push("✅ **Zero target-size violations across all 14 routes.**");
    lines.push("");
    lines.push("Closes audit B-09 for the public marketing + auth surface.");
  } else {
    lines.push(`❌ **${collected.length} violations detected.**`);
    lines.push("");
    lines.push("| Route | Selector | HTML | Failure |");
    lines.push("|---|---|---|---|");
    for (const v of collected) {
      for (const n of v.nodes) {
        const html = n.html.replace(/\|/g, "\\|").slice(0, 80);
        const fail = n.failureSummary.replace(/\n/g, " ").slice(0, 120);
        lines.push(`| \`${v.route}\` | \`${n.target}\` | \`${html}\` | ${fail} |`);
      }
    }
  }
  try {
    fs.writeFileSync(path.join(OUT_DIR, "violations.md"), lines.join("\n"));
  } catch {
    /* read-only fs in container — fall through */
  }
});
