#!/usr/bin/env node
// Phase-16 R5' — ad-hoc <button className="btn ..."> audit.
//
// Walks every .tsx under apps/web/src/pages and apps/web/src/shared.tsx /
// apps/web/src/ui-shell.tsx, finds every JSX <button> whose className
// contains a `btn-*` variant token, and prints a markdown report sorted
// by file then line. Output goes to stdout; redirect into
// docs/AD_HOC_BUTTONS_AUDIT.md to update the audit.
//
// Run from the repo root: `node scripts/audit-buttons.mjs > docs/AD_HOC_BUTTONS_AUDIT.md`.
import { readFileSync, readdirSync, statSync } from "node:fs";
import { join } from "node:path";

const ROOTS = ["apps/web/src/pages", "apps/web/src"];

const walk = (dir) => {
  const out = [];
  for (const name of readdirSync(dir)) {
    const p = join(dir, name);
    const st = statSync(p);
    if (st.isDirectory()) {
      if (name === "node_modules" || name === "ui") continue;
      out.push(...walk(p));
    } else if (name.endsWith(".tsx")) {
      out.push(p);
    }
  }
  return out;
};

const files = new Set();
for (const root of ROOTS) {
  try {
    walk(root).forEach((p) => files.add(p));
  } catch {
    /* root missing — skip */
  }
}

// Match: <button …className="btn …btn-VARIANT [btn-SIZE] …" …>
// Capture: line, raw className contents.
const tag = /<button\b([^>]*?)\bclassName="([^"]*?\bbtn\b[^"]*)"([^>]*)>/g;

const VARIANTS = ["primary", "secondary", "ghost", "outline", "ink", "amber"];
const SIZES = ["sm", "lg", "icon"];

const findings = [];
for (const file of files) {
  const text = readFileSync(file, "utf8");
  let m;
  while ((m = tag.exec(text))) {
    const before = text.slice(0, m.index);
    const line = before.split("\n").length;
    const cls = m[2];
    if (!/\bbtn-/.test(cls)) continue; // skip plain `.btn`-only mismatches
    const variant = VARIANTS.find((v) => new RegExp(`\\bbtn-${v}\\b`).test(cls));
    const size = SIZES.find((s) => new RegExp(`\\bbtn-${s}\\b`).test(cls));
    const extras = cls
      .split(/\s+/)
      .filter((t) => t && t !== "btn" && !/^btn-/.test(t))
      .join(" ");
    findings.push({ file, line, variant: variant || "?", size: size || "md", extras });
  }
}

findings.sort((a, b) =>
  a.file === b.file ? a.line - b.line : a.file.localeCompare(b.file),
);

const total = findings.length;
const byFile = new Map();
for (const f of findings) {
  if (!byFile.has(f.file)) byFile.set(f.file, []);
  byFile.get(f.file).push(f);
}

console.log("# Ad-hoc `<button className=\"btn …\">` audit");
console.log("");
console.log(`Generated by \`scripts/audit-buttons.mjs\`. Total occurrences: **${total}** across **${byFile.size}** files.`);
console.log("");
console.log("Migration target: every match should become `<Button variant=\"…\" size=\"…\">` from `apps/web/src/ui/Button.tsx`. `<a>` tags are out of scope.");
console.log("");
console.log("Variant map (from owner): `btn-primary→primary`, `btn-outline→outline`, `btn-ghost→ghost`, `btn-amber→secondary`, `btn-danger→danger` (synthetic).");
console.log("");
console.log("| File | Line | Variant | Size | Extra classes |");
console.log("|---|---|---|---|---|");
for (const f of findings) {
  console.log(
    `| \`${f.file.replace(/\\/g, "/")}\` | ${f.line} | ${f.variant} | ${f.size} | ${f.extras || "—"} |`,
  );
}
