#!/usr/bin/env bash
# Phase-13 R1 — one-off VPS bootstrap.
#
# Run this ONCE on a fresh VPS (or after a host wipe). It installs the
# wowu/docker-rollout Docker CLI plugin into the deploying user's
# ~/.docker/cli-plugins/, creates /var/backups/digiuniversity/ with the
# right permissions, and installs a daily cron entry that runs the
# backup action through the project's docker container.
#
# Idempotent: rerunning it is safe. Errors abort the whole script so we
# never end up in a half-bootstrapped state.
#
# Usage (from this repo on the VPS, NOT from the Windows dev box):
#   bash scripts/bootstrap-vps.sh
#
# Why not call it from remote.ps1? Because the install touches root-only
# paths (/etc/cron.daily, /var/backups) and prompts for sudo, which the
# remote.ps1 wrapper deliberately avoids. Bootstrap is a host-admin
# task, not a per-deploy task.

set -euo pipefail

ROLLOUT_VERSION="${ROLLOUT_VERSION:-main}"
ROLLOUT_URL="https://raw.githubusercontent.com/wowu/docker-rollout/${ROLLOUT_VERSION}/docker-rollout"
PLUGIN_DIR="${HOME}/.docker/cli-plugins"
BACKUP_DIR="/var/backups/digiuniversity"
PROJECT_DIR="${PROJECT_DIR:-/var/www/digiuniversity}"
CRON_FILE="/etc/cron.d/digiuniversity-backup"

say() { printf '\033[1;36m==>\033[0m %s\n' "$*"; }
warn() { printf '\033[1;33m!! \033[0m %s\n' "$*" >&2; }
die()  { printf '\033[1;31m!!!\033[0m %s\n' "$*" >&2; exit 1; }

# ----------------------------------------------------------------------
# Sanity checks
# ----------------------------------------------------------------------
[[ "$(uname -s)" == "Linux" ]] || die "This script is for the Ubuntu VPS only, not Windows / macOS."
command -v docker >/dev/null 2>&1 || die "docker not found on PATH. Install Docker Engine + Compose plugin first."
docker compose version >/dev/null 2>&1 || die "docker compose plugin not found. Install docker-compose-plugin."

[[ -d "$PROJECT_DIR" ]] || warn "PROJECT_DIR=$PROJECT_DIR does not exist yet — the cron entry assumes the repo is cloned there."

# ----------------------------------------------------------------------
# 1. Install docker-rollout plugin (zero-downtime deploys)
# ----------------------------------------------------------------------
say "Installing docker-rollout plugin into $PLUGIN_DIR"
mkdir -p "$PLUGIN_DIR"
if [[ -x "$PLUGIN_DIR/docker-rollout" ]]; then
    say "  already installed; refreshing"
fi
curl -fsSL "$ROLLOUT_URL" -o "$PLUGIN_DIR/docker-rollout"
chmod +x "$PLUGIN_DIR/docker-rollout"
docker rollout --help >/dev/null 2>&1 || die "docker-rollout did not register as a CLI plugin; check $PLUGIN_DIR/docker-rollout."
say "  docker rollout ok"

# ----------------------------------------------------------------------
# 2. Backup directory
# ----------------------------------------------------------------------
say "Preparing backup directory $BACKUP_DIR"
sudo mkdir -p "$BACKUP_DIR"
sudo chown root:docker "$BACKUP_DIR" 2>/dev/null || sudo chown root:root "$BACKUP_DIR"
sudo chmod 0750 "$BACKUP_DIR"
say "  $(ls -ld $BACKUP_DIR)"

# ----------------------------------------------------------------------
# 3. Nightly backup cron
# ----------------------------------------------------------------------
say "Installing nightly backup cron at $CRON_FILE"
sudo tee "$CRON_FILE" >/dev/null <<EOF
# Phase-13 R1 — nightly pg_dump of digiuniversity-postgres, gzipped, 14-day rotation.
# Generated by scripts/bootstrap-vps.sh. Edit the script and re-run; do not edit
# this file in place (it will get overwritten on the next bootstrap).
SHELL=/bin/bash
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
15 3 * * * root TS=\$(date +\\%F-\\%H\\%M\\%S); OUT=$BACKUP_DIR/digi-\$TS.sql.gz; docker exec digiuniversity-postgres pg_dump -U digiuniversity -d digiuniversity --no-owner --no-privileges 2>>/var/log/digiuniversity-backup.log | gzip -9 > "\$OUT" && ls -1t $BACKUP_DIR/*.sql.gz 2>/dev/null | tail -n +15 | xargs -r rm
EOF
sudo chmod 0644 "$CRON_FILE"
sudo touch /var/log/digiuniversity-backup.log
sudo chmod 0640 /var/log/digiuniversity-backup.log
say "  cron entry installed; first run at 03:15 server time"

# ----------------------------------------------------------------------
# 4. Summary
# ----------------------------------------------------------------------
say "Bootstrap complete."
cat <<EOF

Verification:
  docker rollout --help            # plugin is callable
  ls -ld $BACKUP_DIR               # exists, mode 0750
  sudo cat $CRON_FILE              # cron present
  sudo systemctl status cron       # cron daemon is active

From your Windows dev box you can now run:
  .\\scripts\\remote.ps1 backup                 # one-off backup, 14-day rotation
  .\\scripts\\remote.ps1 health                 # probe all four services
  .\\scripts\\remote.ps1 rollout -Service api   # zero-downtime update
  .\\scripts\\remote.ps1 rollback               # safe git-revert rollback

EOF
